name: aplikacja_pogodowa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:

  sdk: ">=2.17.1 <3.0.5"  # sdk: ">=2.17.1 <3.0.5"



dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.6.0
  retrofit: '>=3.0.0 <4.0.0'
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  collection: ^1.16.0
  provider: ^6.0.3
  intl: ^0.17.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_lints: ^2.0.0
  json_serializable: '>4.4.0'
  build_runner: any 
  hive_generator: ^1.0.1
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
